ALTER TABLE "Warehouse"
ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "WarehouseStaffProfile"
ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "DriverProfile"
ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
